- name: Update network settings
  hosts: server
  become: true
  vars_files:
    - config.yml
  roles:
    - setup_network

- name: Install and configure ipsec packages
  hosts: server
  become: true
  become_method: sudo
  vars_files:
    - config.yml
  roles:
    - setup_ipsec
    - setup_xl2tpd
    - setup_ppp
    - activate_autostart
    - restart_services
