- name: Enable NAT
  iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE

- name: Enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Get ipv4 interfaces
  command: ls /proc/sys/net/ipv4/conf/
  register: ipv4_interfaces
  changed_when: false

- name: Disable sending and acceptance of ICMP redirected packets on all ipv4 interfaces
  sysctl:
    name: 'net.ipv4.conf.{{ item.0 }}.{{ item.1 }}'
    value: 0
    sysctl_set: yes
    state: present
    reload: yes
  with_nested:
   - "{{ ipv4_interfaces.stdout_lines }}"
   - [ 'accept_redirects',  'send_redirects' ]

- name: Update rc.local
  blockinfile:
    name: /etc/rc.local
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertbefore: "exit 0"
    content: |
      for vpn in /proc/sys/net/ipv4/conf/*; do echo 0 > $vpn/accept_redirects; echo 0 > $vpn/send_redirects; done
      iptables --table nat --append POSTROUTING --jump MASQUERADE
