# - name: Install openswan
#   apt:
#     name: openswan
#     state: present

- name: Install openswan version 2.6.37–3
  apt:
    deb: http://snapshot.raspbian.org/201403301125/raspbian/pool/main/o/openswan/openswan_2.6.37-3_armhf.deb

- name: Copy config file
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    mode: 0644

- name: Set ipsec secret
  lineinfile:
    dest: /etc/ipsec.secrets
    line: '"{{ network.address }}" %any: PSK "{{ credentials.secret }}"'
